config/routes.rb
Commentclubbers::Application.routes.draw do
  get "profiles/show"
  resources :statuses

  devise_for :users
  root "pages#home"
  get "about" => "pages#about" # creates about_path

  get '/:id', to: 'profiles#show'

end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :statuses
  has_many :user_friendships
  has_many :friends, through: :user_friendships


  def full_name 
  	first_name + " " + last_name
  end

  def gravatar_url
  	stripped_email = email.strip
  	downcased_email = stripped_email.downcase
  	hash = Digest::MD5.hexdigest(downcased_email)

  	"http://gravatar.com/avatar/#{hash}"
  end

end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
	belongs_to :user 
	belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception


  protected


    def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :profile_name, 
                  :email, :password, :password_confirmation) }
    end


end
  

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_profile_name(params[:id])
  	if @user
  		@statuses = @user.statuses.all
  		render action: :show
  	else
  		render file: 'public/404', status: 404, formats: [:html]
  	end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :content, :user_id)
    end
end

app/controllers/user_friendships_controller.rb
class UserFriendshipsController < ApplicationController

	def friend_params
      params.require(:friend).permit(:friend, :user, :user_id, :friend_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def dat_markdown(text)
	  options = {
	    :autolink => true,
	    :space_after_headers => true,
	    :no_intra_emphasis => true
	  }
	  markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, options)
	  markdown.render(text).html_safe
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper	
end

app/helpers/user_friendships_helper.rb
module UserFriendshipsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="#">Home</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", 		'#' %></li>		
			<li><%= link_to "Contact", 	'#' %></li>
			<li><%= link_to "Team", 		'#' %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Comment Clubbers", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>

        <% if user_signed_in? %>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Community", statuses_path %></li>

          <li><%= link_to current_user.full_name, profiles_show_path %></li>

          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.goolgecode.com/svn/trunk/html5.js"></script>
  <![endif]--> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Commentclubbers</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= render 'layouts/shim' %>

</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
		<!-- <%= render 'layouts/footer' %> -->
		<!-- <%= debug(params) %> -->
	</div> 
</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
	<h1>About Us</h1>
	<p>Comment Clubbers is an online community that allows established and new bloggers to gain momentum on their blog posts by giving and receiving quality comments on their blogs.</p>

	<h2>You're inside Comment Clubbers v.1</h2>

	<p>This is the first ever version of Comment 	Clubbers. We'll be launching the full version soon, but for now, you can create an account, sign in, and connect with other comment club members through a community chat area.
	</p>

	<p>Comment Clubbers was born when Brooklyn Fisher first created the facebook group where bloggers were able to share links to their blog posts and exchange quality comments.</p> 

	
	<p>Since then, the club has grown so much that the team decided to build a separate platform! Here it is!
	</p>

	<p>This platform is being built by non-techies- a couple of designers who are NOT programmers to begin with, who have learned to code through this project. The platform will get better and better as the CC team adds key features and incorporate various forms of user feedback.
	</p>


</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome.</h1>

	<% if !user_signed_in? %>
		<h2>Become a Comment Clubber today.</h2>
	<% end %>

	<% if user_signed_in? %>
		<h2>You are now a member of Comment Clubbers. Congratulations!</h2>
		<%= link_to "Leave A Comment", new_status_path, class: "btn btn-primary btn-lg" %><p>
		<p>
		<%= link_to "Browse Comments", statuses_path, class: "btn btn-warning btn-lg" %><p>
	<% else %>

		<p>
			<%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-lg" %>
			<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		</p>
	<% end %>

</div>

app/views/profiles/show.html.erb
<div class="page-header">
	<h1><%= @user.full_name %></h1>
</div>
<div class="span1">
  <%= image_tag @user.gravatar_url %>
</div>

<% if @statuses %>
	<% @statuses.each do |status| %>
		<div class="well">
			<%= status.content %>
			<hr />
			<%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
		</div>
	<% end %>
<% end %>

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
 </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :Submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
  <h1>Post Your Link</h1>
</div>

<%= link_to 'Post Link Here', new_status_path, class: "btn btn-success" %><p>

<% @statuses.each do | status | %>
<div class="status">
    <div class="span1">
      <%= image_tag status.user.gravatar_url %>
    </div>
    <div class="span5">
      <strong><%= status.user.full_name %></strong>
      <p><%= dat_markdown(status.content) %></p>
      <div class="meta">
        <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
        <span class="admin">
          | <%= link_to "Edit", edit_status_path(status) %> |
          <%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure you want to delete this status?"} %>
        </span>
      </div>
    </div>
</div>

<% end %>

app/views/statuses/new.html.erb
<h1>Post Your Link</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.user.full_name %>
</p>


<p>
  <strong>Content:</strong>
  <%= dat_markdown(@status.content) %>
</p>

<%= link_to 'Edit', edit_status_path(@status), class: "btn btn-default" %>  
<%= link_to 'See Statuses', statuses_path, class: "btn btn-primary" %>